export const pricingData = [
  {
    category: "Estetică dentară",
    items: [
      { name: "Albire profesională endodontică (internă / dinte)", price: "300 RON" },
      { name: "Albire profesională în cabinet Opalescence H2O2 40%", price: "750 RON" },
      { name: "Albire profesională în cabinet Bleach’n Smile H2O2 35%", price: "960 RON" },
      { name: "Albire profesională cu lampa Philips Zoom H2O2 6%", price: "1700 RON" },
      { name: "Aplicare bijuterii dentare pe suprafața smalțului", price: "220 RON" },
      { name: "Albire laser", price: "1200 RON" },
    ],
  },
  {
    category: "Estetică facială",
    items: [
      { name: "Injectări cu Acid Hyaluronic Juvederm Ultra 3", price: "1450 RON" },
      { name: "Injectări cu Acid Hyaluronic Juvederm Ultra Smile", price: "1300 RON" },
      { name: "Botox (3 zone)", price: "1500 RON" },
      { name: "Gummi line botox (zâmbet gingival)", price: "750 RON" },
    ],
  },
  {
    category: "Consultații primare și de specialitate",
    items: [
      { name: "Consultație stomatologică generală, realizare fișă completă, întocmire plan tratament", price: "150 RON" },
      { name: "Consultație și diagnostic parodontologic, status parodontal", price: "250 RON" },
      { name: "Consultație și diagnostic implantologie, interpretare CT", price: "180 RON" },
      { name: "Realizarea modelului documentar", price: "120 RON" },
      { name: "Consultație și diagnostic ortodontic", price: "250 RON" },
      { name: "Consultație pediatrică", price: "200 RON" },
    ],
  },
  {
    category: "Profilaxie și prevenție",
    items: [
      { name: "Periaj profesional", price: "80 RON" },
      { name: "Detartraj ultrasonic supragingival", price: "200 RON" },
      { name: "Fluorizare / tratament desensibilizare / dinte", price: "30 RON" },
      { name: "Airflow", price: "200 RON" },
      { name: "Airflow cu particule de glicină", price: "250 RON" },
      { name: "Ședință completă igienizare (Detartraj + Periaj + Airflow)", price: "380 RON" },
      { name: "Igienizare pe implante cu îndepărtarea lucrării", price: "500 RON" },
      { name: "Igienizare pedodontică", price: "250 RON" },
      { name: "Sigilare șanțuri și fosete dinți temporari / dinte", price: "180 RON" },
      { name: "Sigilare șanțuri și fosete dinți permanenți / dinte", price: "250 RON" },
    ],
  },
  {
    category: "Tratamente odontale / obturații",
    items: [
      { name: "Obturație ionomer", price: "140 - 170 RON" },
      { name: "Coafaj cu Hidroxid de Ca", price: "90 RON" },
      { name: "Obturație EQUIA", price: "260 RON" },
      { name: "Coafaj cu MTA", price: "140 RON" },
      { name: "Aplicare sistem de izolare – Diga", price: "50 RON" },
      { name: "Obturație fizionomică compozit mică", price: "380 RON" },
      { name: "Obturație fizionomică compozit medie", price: "430 RON" },
      { name: "Obturație fizionomică compozit mare", price: "470 RON" },
      { name: "Obturație dinți frontali", price: "490 RON" },
      { name: "Obturație Biodentine", price: "360 RON" },
      { name: "Reconstrucție cu compozit fotopolimerizabil", price: "250 RON" },
      { name: "Refacere fațetă vestibulară – compozit foto", price: "550 RON" },
      { name: "Obturație colet", price: "250 RON" },
      { name: "Obturație ZOE", price: "120 RON" },
    ],
  },
  {
    category: "Tratamente laser",
    items: [
      { name: "Biomodulare / ședință", price: "250 RON" },
      { name: "Tratament de desensibilizare", price: "200 RON" },
      { name: "Igienizare laser", price: "1250 RON" },
      { name: "DSR asistat laser / dinte / implant", price: "250 RON" },
      { name: "DSR asistat laser / hemiarcadă", price: "900 RON" },
      { name: "Frenectomie laser", price: "750 RON" },
      { name: "Decapușonare / dinte", price: "250 RON" },
      { name: "Gingivectomie / dinte", price: "250 RON" },
      { name: "Gingivoplastie / dinte", price: "275 RON" },
      { name: "Tratament laser periimplantită", price: "500 RON" },
      { name: "Stimularea vindecării gingivale / ședință", price: "200 RON" },
      { name: "Excizii formațiuni endoorale", price: "600 RON" },
      { name: "Tratament inflamația sinusului maxilar", price: "300 RON" },
      { name: "Tratament ATM", price: "300 RON" },
      { name: "Tratamentul durerilor postextracționale", price: "300 RON" },
    ],
  },
  {
    category: "Pedodonție",
    items: [
      { name: "Pachet anual pedodonție", price: "990 RON" },
      { name: "Ședință de acomodare", price: "150 RON" },
      { name: "Sigilare șanțuri și fosete dinți temporari / dinte", price: "180 RON" },
      { name: "Fluorizare ambele arcade", price: "200 RON" },
      { name: "Obturație glassionomer", price: "200 RON" },
      { name: "Obturație compozit", price: "200 RON" },
      { name: "Aplicare pansament devitalizant", price: "180 RON" },
      { name: "Aplicare pansament calmant", price: "180 RON" },
      { name: "Aplicare pansament antiseptic", price: "180 RON" },
      { name: "Pulpectomie vitală dinți temporari", price: "200 RON" },
      { name: "Pulpectomie devitală dinți temporari", price: "250 RON" },
      { name: "Pulpotomie dinte temporar", price: "250 RON" },
      { name: "Coroniță pedodontică", price: "375 RON" },
      { name: "Tratament endodontic dinte temporar", price: "350 RON" },
      { name: "Obturație canal dinți temporari", price: "200 RON" },
      { name: "Extracție dinte temporar monoradicular", price: "280 RON" },
      { name: "Extracție dinte temporar pluriradicular", price: "300 RON" },
    ],
  },
  {
    category: "Endodonție",
    items: [
      { name: "Tratament canal monoradicular", price: "350 RON" },
      { name: "Obturație endodontică monoradicular", price: "250 RON" },
      { name: "Tratament canal premolar", price: "430 RON" },
      { name: "Obturație endodontică premolar", price: "300 RON" },
      { name: "Tratament canal pluriradicular", price: "470 RON" },
      { name: "Tratament canal molar de minte", price: "590 RON" },
      { name: "Reparare perforații radiculare cu MTA / bioceramică", price: "180 RON" },
      { name: "Retratament monoradicular", price: "410 RON" },
      { name: "Retratament pluriradicular", price: "650 RON" },
      { name: "Retratament molar de minte", price: "750 RON" },
      { name: "Pivot fibră de sticlă", price: "300 RON" },
    ],
  },
  {
    category: "Protetică dentară",
    items: [
      { name: "Coroană provizorie acrilică", price: "100 RON" },
      { name: "Coroană PMMA CAD-CAM", price: "350 RON" },
      { name: "Coroană metalică", price: "300 RON" },
      { name: "Coroană metalo-ceramică", price: "1200 RON" },
      { name: "Coroană integral ceramică Emax", price: "1800 RON" },
      { name: "Coroană zirconiu CAD-CAM", price: "1700 - 2500 RON" },
      { name: "Inlay / Onlay compozit", price: "800 RON" },
      { name: "Incrustație ceramică", price: "1400 RON" },
      { name: "Gutieră bruxism", price: "400 RON" },
      { name: "Proteză acrilică totală / arcadă", price: "2500 - 3100 RON" },
      { name: "Proteză elastică", price: "3200 - 3800 RON" },
      { name: "Structură Ibar compozit", price: "15000 RON" },
      { name: "Structură Ibar zirconiu", price: "25000 RON" },
      { name: "Proteză scheletată", price: "de la 3900 RON" },
      { name: "Coroană metalo-ceramică pe implant", price: "1750 RON" },
      { name: "Coroană zirconiu pe implant", price: "2250 RON" },
      { name: "Coroană metalo-ceramică pe implant înșurubată", price: "400 EURO" },
    ],
  },
  {
    category: "Ortodonție",
    items: [
      { name: "Aparat monomaxilar mobilizabil", price: "1200 RON" },
      { name: "Aparat bimaxilar funcțional", price: "1200 RON" },
      { name: "Aparat fix metalic / arcadă", price: "3000 RON" },
      { name: "Aparat fix metalic / ambele arcade", price: "6000 RON" },
      { name: "Aparat fix ceramic / arcadă", price: "4000 RON" },
      { name: "Aparat fix ceramic / ambele arcade", price: "8000 RON" },
      { name: "Aparat fix safir / arcadă", price: "4500 RON" },
      { name: "Aparat fix safir / ambele arcade", price: "9000 RON" },
      { name: "Disjunctor", price: "1500 RON" },
      { name: "Disjunctor pe implant", price: "5500 RON" },
      { name: "Activare aparat fix metalic / arcadă", price: "150 RON" },
      { name: "Activare aparat fix fizionomic / arcadă", price: "200 RON" },
      { name: "Contenție fixă", price: "300 RON" },
      { name: "Contenție gutieră / placă Howley", price: "400 RON" },
    ],
  },
  {
    category: "Alignere",
    items: [
      { name: "Spark 10 / arcadă", price: "6000 RON" },
      { name: "Spark 10 / ambele arcade", price: "10000 RON" },
      { name: "Spark 20 / arcadă", price: "11500 RON" },
      { name: "Spark 20 / ambele arcade", price: "15000 RON" },
      { name: "Spark Advanced / ambele arcade", price: "20000 RON" },
      { name: "Plan tratament 3D Spark", price: "1300 RON" },
      { name: "Angel Aligner", price: "tarif după evaluare" },
    ],
  },
  {
    category: "Implantologie",
    items: [
      { name: "Implant INNO", price: "400 EURO" },
      { name: "Implant MegaGen AnyRidge", price: "500 EURO" },
      { name: "Implant Neodent Acqua", price: "500 EURO" },
      { name: "MIS Seven", price: "500 EURO" },
      { name: "MIS C1", price: "600 EURO" },
      { name: "Implant Straumann BLT", price: "700 EURO" },
      { name: "Implant Straumann BLX", price: "900 EURO" },
      { name: "Sinus lift extern fără biomateriale", price: "3000 RON" },
      { name: "Sinus lift intern fără biomateriale", price: "1500 RON" },
      { name: "Ridge split fără biomateriale", price: "1300 RON" },
      { name: "Adiție os fără biomateriale", price: "1500 RON" },
      { name: "Recoltare os autolog", price: "1100 RON" },
      { name: "PRF", price: "660 RON" },
    ],
  },
  {
    category: "All-on-4 / All-on-6",
    items: [
      { name: "All-on-4 INNO", price: "2000 EURO" },
      { name: "All-on-4 Neodent", price: "3000 EURO" },
      { name: "All-on-4 Straumann", price: "5000 EURO" },
      { name: "All-on-6 INNO", price: "3500 EURO" },
      { name: "All-on-6 Neodent", price: "4000 EURO" },
      { name: "All-on-6 Straumann", price: "6000 EURO" },
    ],
  },
  {
    category: "Chirurgie dento-alveolară",
    items: [
      { name: "Extracție dinte temporar", price: "120 RON" },
      { name: "Extracție dinte monoradicular", price: "280 RON" },
      { name: "Extracție dinte pluriradicular", price: "300 RON" },
      { name: "Extracție molar de minte erupt", price: "450 RON" },
      { name: "Extracție dinte parodontotic", price: "220 RON" },
      { name: "Extracție cu alveolotomie", price: "350 RON" },
      { name: "Extracție rest radicular", price: "230 RON" },
      { name: "Odontectomie incluzie maxilar", price: "600 RON" },
      { name: "Odontectomie incluzie mandibulă", price: "700 RON" },
      { name: "Chistectomie <2cm", price: "450 RON" },
      { name: "Chistectomie >2cm", price: "650 RON" },
    ],
  },
  {
    category: "Chirurgie endodontică / preprotetică",
    items: [
      { name: "Rezecție apicală monoradicular", price: "500 RON" },
      { name: "Rezecție apicală pluriradicular", price: "600 RON" },
      { name: "Rezecție apicală + obturație retro monoradicular", price: "700 RON" },
      { name: "Rezecție apicală + obturație retro pluriradicular", price: "800 RON" },
      { name: "Chiuretaj apico-periapical", price: "400 RON" },
      { name: "Premolarizare", price: "400 RON" },
      { name: "Incizie și drenaj abces", price: "280 RON" },
      { name: "Frenectomie / Frenoplastie / Bride", price: "300 RON" },
      { name: "Vestibuloplastie", price: "500 RON" },
    ],
  },
  {
    category: "Chirurgie maxilo-facială",
    items: [
      { name: "Excizie formațiune tumorală piele", price: "420 RON" },
      { name: "Excizie formațiune tumorală mucoasă", price: "420 RON" },
      { name: "Excizie chist sebaceu / fibrolipom", price: "385 RON" },
      { name: "Excizie cicatrici piele", price: "520 RON" },
      { name: "Lip repositioning", price: "1440 RON" },
      { name: "Corticotomii per dinte", price: "380 RON" },
      { name: "Corticotomii per segment", price: "500 RON" },
      { name: "Reducere și imobilizare fracturi proces alveolar", price: "500 RON" },
      { name: "Reducere și imobilizare fracturi mandibulă / maxilar", price: "1500 RON" },
      { name: "Reducere și imobilizare fracturi oase nazale", price: "960 RON" },
      { name: "Incizie și drenaj abces submandibular", price: "960 RON" },
      { name: "Biopsie os", price: "480 RON" },
      { name: "Tratament urgență trigemeni", price: "240 RON" },
      { name: "Bichectomie unilaterală", price: "1500 RON" },
      { name: "Bichectomie bilaterală", price: "2900 RON" },
    ],
  },
];

